name: Lighthouse
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  statuses: write

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          # En PR, audita el commit real del PR (no el merge commit)
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}

      - name: Audit URLs using Lighthouse CI
        uses: treosh/lighthouse-ci-action@v12
        env:
          # Evita el error de "git rev-parse HEAD" aunque haya edge cases
          LHCI_BUILD_CONTEXT__CURRENT_HASH: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
          LHCI_BUILD_CONTEXT__CURRENT_BRANCH: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}
          LHCI_BUILD_CONTEXT__GITHUB_REPO_SLUG: ${{ github.repository }}
        with:
          urls: |
            https://joseaperalta.github.io/Seminaro-testing/
          uploadArtifacts: true
          temporaryPublicStorage: true
          artifactName: lighthouse-results


