name: Análisis con SonarQube (SonarCloud)
on:
  push:
    branches: [ main ]
jobs:
  sonar:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: Instalar dependencias
        run: npm ci
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1
        with:
          projectKey: "<mi-usuario>_<mi-repo>"
          organization: "<mi-organizacion>"
          token: ${{ secrets.SONAR_TOKEN }}
