name: web-pipeline

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  lint:
    uses: ./.github/workflows/lint_and_format.yml
    with:
      node-version: "24"

  test:
    uses: ./.github/workflows/test.yml
    with:
      node-version: "24"

  links:
    needs: [lint, test]
    uses: ./.github/workflows/links.yml

  optimize:
    needs: [lint, test]
    uses: ./.github/workflows/optimize.yml
    with:
      node-version: "24"
      build-dir: "."

  lighthouse:
    needs: [links, optimize]
    uses: ./.github/workflows/lighthouse.yml
    with:
      build-dir: "."

  deploy:
    needs: [links, optimize]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    with:
      build-dir: "."
